QnA_System/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('QnAbase.urls')),
    path('admin/', admin.site.urls),
]

QnAbase/urls.py
from django.urls import path
from .views import *

app_name = 'QnAbase'

urlpatterns = [
    path('', home, name="home"),
    path('detail/<int:id>', detail,name='detail'),
    path('signup', signup, name='signup'),
    path('signin', signin, name='signin'),
    path('activate/<uidb64>/<token>',activate, name='activate'),
    path('save-comment', save_comment,name='save-comment'),
    path('save-upvote', save_upvote,name='save-upvote'),
    path('save-downvote', save_downvote,name='save-downvote'),
    path('ask-question', ask_form,name='ask-question'),
    # path('add-blog/', add_blog, name="add_blog"),
    path('logout-view', logout_view, name="logout_view")
]

QnAbase/models.py
from django.db import models
from django.contrib.auth.models import User,AbstractUser

# class CustomUser(AbstractUser):
#     bio=models.TextField()
#     location=models.CharField(max_length=200)

# question model
class Question(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    title = models.CharField(max_length=1000)
    # detail = models.TextField()
    add_time = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.title
#Answer Model
class Answer(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    detail = models.TextField()
    add_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.detail
    
class Comment(models.Model):
    answer = models.ForeignKey(Answer,on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comment_user')
    comment = models.TextField(default=' ')
    add_time = models.DateTimeField(auto_now_add=True)

class Upvote(models.Model):
    answer = models.ForeignKey(Answer,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE, related_name='upvote')
    
class Downvote(models.Model):
    answer = models.ForeignKey(Answer,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE, related_name='downvote')
    

templates/ask-question.html
{% extends 'base.html' %}
{% block title %}Ask Question{% endblock %}
{% block start %}
<div class="container">
    <div class="card mt-5">
        <h5 class="card-header">Ask Your Question</h5>
        <div class="card-body">
            {% for msg in messages %}
            <p class="text-success">{{msg}}</p>
            {% endfor %}
            <form method="post">
                {% csrf_token %}
                    <div class="col-md-12">
                        <input type="text" class="form-control" placeholder="Enter question" name="title">
                    </div>
                    <div>
                        <div class="text-center mt-3">
                            <button class="btn btn-primary">Submit</button>
                        </div>
                    </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}AskMe{% endblock %}</title>
    <!-- Animate 4 -->
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}" />
    <!-- Bootstrap 4 -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <!-- Font Awesome 4 -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/signin.css' %}" />
    <!-- Jquery -->
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <!-- Bootstrap 4 Js -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="/">AskMe</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <form class="ml-auto" action="/">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="Search" />
                        <div class="input-group-append">
                        <button class="btn btn-success" type="submit" id="button-addon2">Search</button>
                        </div>
                    </div>
                </form>
                <ul class="navbar-nav ml-auto">
                   
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'QnAbase:ask-question' %}">Asked Your Question</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'QnAbase:logout_view' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'QnAbase:signin' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'QnAbase:signup' %}">Register</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    {% block start %}
    {% endblock %}
</body>
</html>

templates/detail.html
{% extends "base.html" %}
{% load static %} {% load humanize %}
{% block start %}
    <!-- Search Section -->
    <div class="container">
      <h2 class="my-4">{{quest.title}}</h2>
      <p>
        <span class="my-4">{{quest.add_time|date:'d/m/Y'}}</span>
        <a href="#">{{quest.user.username}}</a>
      </p>
      <hr />

      {% for answer in answers %}
      <div class="row">
        <div class="col-1" style="text-align: center">
          <div class="upvote">
            <strong class="upvote-count-{{answer.id}}"
              >{{answer.upvote_set.count}}</strong
            ><br />
            <span class="text-success">
              <i
                class="fa fa-arrow-up fa-2x upvote-click"
                data-answer="{{answer.id}}"
              ></i>
            </span>
          </div>
          <div class="downvote mt-3">
            <span class="text-danger">
              <i
                class="fa fa-arrow-down fa-2x downvote-click"
                data-answer="{{answer.id}}"
              ></i> </span
            ><br />
            <strong class="downvote-count-{{answer.id}}"
              >{{answer.downvote_set.count}}</strong
            >
          </div>
        </div>
        <div class="col-11">
            <p>
                <strong class="my-4 ">Answer</strong>
                by <a href="#" class="mr-3">{{answer.user.username}}</a>
              </p>
          <p>{{ answer.detail }}</p>
          <p>
            <span class="mr-3"
              ><span class="comment-count-{{answer.id}}"
                >{{answer.comment_set.count}}</span
              >
              comments</span
            >
            <span class="mr-3">{{answer.add_time|date:'d/m/Y h:i:s'}}</span>
            
          </p>
          <!-- Comment Section Start -->

          <div class="comment-wrapper-{{answer.id}}">
            {% for comment in answer.comment_set.all %}
            <div class="card mb-2">
              <div class="card-body">
                <p>{{comment.comment}}</p>
                <p>
                  <a href="#">{{comment.user.username}}</a>
                </p>
              </div>
            </div>
            {% endfor %}
          </div>
          {% if user.is_authenticated %}
          <!-- Comment Form -->
          <div class="card my-3">
            <h6 class="card-header">Add Comment</h6>
            <div class="card-body">
              <textarea
                class="form-control comment-text-{{answer.id}}"
              ></textarea>
              <button
                type="button"
                data-answer="{{answer.id}}"
                class="btn btn-dark my-3 save-comment"
              >
                Submit
              </button>
            </div>
          </div>
          {% endif %}
        </div>
      </div>
      <hr />
      {% endfor %} {% if user.is_authenticated %} {% for msg in messages %}
      <p class="text-success">{{msg}}</p>
      {% endfor %}
      <form method="post">
        {% csrf_token %}
        <table class="table table-bordered">
          {{answerform.as_table}}
          <tr>
            <td colspan="2">
              <input type="submit" class="btn btn-dark" />
            </td>
          </tr>
        </table>
      </form>
      {% endif %}
    </div>
    <script src="{% static '/js/jquery-3.5.1.min.js' %}"></script>
    <script>
      $(document).ready(function(){
        $(".save-comment").on('click',function(){
            var _answerid=$(this).data('answer');
            var _comment=$(".comment-text-"+_answerid).val();
            // Ajax
            $.ajax({
                url:"/save-comment",
                type:"post",
                data:{
                    comment:_comment,
                    answerid:_answerid,
                    csrfmiddlewaretoken:"{{csrf_token}}"
                },
                dataType:'json',
                beforeSend:function(){
                    $(".save-comment").addClass('disabled').text('saving...');
                },
                success:function(res){
                    if(res.bool==true){
                        $(".comment-text-"+_answerid).val('');
                        // Append Element
                        var _html='<div class="card mb-2 animate__animated animate__bounce">\
                        <div class="card-body">\
                            <p>'+_comment+'</p>\
                            <p>\
                                <a href="#">{{request.user}}</a>\
                            </p>\
                        </div>\
                    </div>';
                    $(".comment-wrapper-"+_answerid).append(_html);
                    var prevCount=$(".comment-count-"+_answerid).text();
                    $(".comment-count-"+_answerid).text(parseInt(prevCount)+1);
                    }
                    $(".save-comment").removeClass('disabled').text('Submit');
                }
            });
        });

        // Upvote
        $(".upvote-click").on('click',function(){
            var answerid=$(this).data('answer');
            // Ajax
            $.ajax({
                url:"/save-upvote",
                type:"post",
                data:{
                    answerid:answerid,
                    csrfmiddlewaretoken:"{{csrf_token}}"
                },
                dataType:'json',
                success:function(res){
                    var _prevupvote=$(".upvote-count-"+answerid).text();
                    if(res.bool==true){
                        $(".upvote-count-"+answerid).text(parseInt(_prevupvote)+1);
                    }
                }
            });
        });

        // Downvote
        $(".downvote-click").on('click',function(){
            var answerid=$(this).data('answer');
            // Ajax
            $.ajax({
                url:"/save-downvote",
                type:"post",
                data:{
                    answerid:answerid,
                    csrfmiddlewaretoken:"{{csrf_token}}"
                },
                dataType:'json',
                success:function(res){
                    var _prevupvote=$(".downvote-count-"+answerid).text();
                    if(res.bool==true){
                        $(".downvote-count-"+answerid).text(parseInt(_prevupvote)+1);
                    }
                }
            });
        });
    });
    </script>
    {% endblock %}

templates/email_confirmation.html
{% autoescape off %}

Hello {{ name }}

Welcome to AskMe 

Please confirm your email by clicking on the following link for login in AskMe .


Confirmation Link: http://{{ domain }}{% url 'QnAbase:activate' uidb64=uid token=token %}

{% endautoescape %}

templates/home.html
{% extends "base.html" %} {% block start %}

<!-- Question List -->

<div class="container">
  {% for quest in quests %}
  <div class="card mb-4 shadow" style="
  margin-top: 20px;">
    <div class="card-body">
      <h4 class="card-title">
        <a href="/detail/{{quest.id}}">{{quest.title}}</a>
      </h4>
      <p class="card-text">{{quest.detail}}</p>
      <p>
        <a href="#" class="mr-2">{{quest.user.username}}</a>
        <a href="#" class="mr-2">{{quest.answer_set.count}} Answers</a>
        <a href="#" class="mr-2">{{quest.total_comments}} Comments</a>
      </p>
    </div>
    <div class="card-footer">
      <small>{{quest.add_time}}</small>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}

templates/signin.html
{% extends "base.html" %}

{% block start %}
  {% for message in messages %}
    <div class = "container">
      <div class="alert alert-{{ message.tags }} alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>Message: </strong> {{ message }}
      </div>
    </div>
  {% endfor %}
<div class="wrapper">
  <div class="text-center mt-4 name">
      Sign In Your Account
  </div>
  <form class="p-3 mt-3" form action="/signin" method="post" >
    {% csrf_token %}
      <div class="form-field d-flex align-items-center">
        <input type="text" name="username" id="userName" placeholder="Username" autocomplete="off">
      </div>
      <div class="form-field d-flex align-items-center">
        <input type="password" name="pass1" id="pwd" placeholder="Password" autocomplete="off">
      </div>
      <button class="btn mt-3" type="submit">Sign in</button>
  </form>
  <div class="text text-center fs-6">
    <a href="{% url 'QnAbase:signup' %}">Create an Account</a>
  </div>
</div>

{% endblock %}
  

templates/signup.html
{% extends "base.html" %} {% block start %}
  {% for message in messages %}
    <div class = "container">
      <div class="alert alert-{{ message.tags }} alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>Message: </strong> {{ message }}
      </div>
    </div>
  {% endfor %}
<div class="wrapper">
  <div class="text-center mt-4 name">
      Create Your Account
  </div>
  <form class="p-3 mt-3" form action="/signup" method="post" >
    {% csrf_token %}
      <div class="form-field d-flex align-items-center">
        <input type="text" name="username" id="userName" placeholder="Username" autocomplete="off" required>
      </div>
      <div class="form-field d-flex align-items-center">
        <input type="text" name="fname" id="userName" placeholder="First Name" autocomplete="off" required>
      </div>
      <div class="form-field d-flex align-items-center">
        <input type="text" name="lname" id="userName" placeholder="Last Name" autocomplete="off" required>
      </div>
      <div class="form-field d-flex align-items-center">
        <input type="email" name="email" id="userName" placeholder="Email Address" autocomplete="off"required>
      </div>
      <div class="form-field d-flex align-items-center">
        <input type="password" name="pass1" id="pwd" placeholder="Password" autocomplete="off" required>
      </div>
      <div class="form-field d-flex align-items-center">
        <input type="password" name="pass2" id="pwd" placeholder="Confirm Password" autocomplete="off" required>
      </div>
      <button class="btn mt-3 " type="submit">Sign up</button>
  </form>
  <div class="text text-center fs-6">
      I have an account. <a href="{% url 'QnAbase:signin' %}">Sign in</a>
  </div>
</div>


{% endblock %}